module.exports = {
  LOAD_REPOSITORIES: 'LOAD_REPOSITORIES',
  LOAD_REPOSITORY_INDEX: 'LOAD_REPOSITORY_INDEX',
  LOAD_REPOSITORY_DOCUMENT: 'LOAD_REPOSITORY_DOCUMENT',
  SELECT_REPOSITORY: 'SELECT_REPOSITORY',
  SELECT_REPOSITORY_BRANCH: 'SELECT_REPOSITORY_BRANCH',
  SELECT_REPOSITORY_INDEX_ITEM: 'SELECT_REPOSITORY_INDEX_ITEM',
  SEARCH_REPOSITORY_INDEX_ITEM: 'SEARCH_REPOSITORY_INDEX_ITEM'
};
