module.exports = {
  LOAD_REPOSITORIES: 'LOAD_REPOSITORIES',
  LOAD_REPOSITORY_INDEX: 'LOAD_REPOSITORY_INDEX',
  SELECT_REPOSITORY: 'SELECT_REPOSITORY',
  SELECT_REPOSITORY_BRANCH: 'SELECT_REPOSITORY_BRANCH'
};
